import html
import io
import os
import re
from collections import Counter

import streamlit as st
from dotenv import load_dotenv
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.platypus import PageBreak, Paragraph, SimpleDocTemplate, Spacer

from agents.claims_agent import run_claims_agent
from agents.common import DEFAULT_MODEL, run_gemini
from agents.evaluation_agent import run_evaluation_agent
from agents.methodology_agent import run_methodology_agent
from agents.report_agent import generate_final_report
from agents.research_mentor_agent import run_research_mentor_agent
from agents.safety_agent import run_safety_agent
from agents.summary_agent import run_summary_agent
from utils.gemini_client import get_gemini_client
from utils.pdf_reader import extract_pages_from_pdf, get_pdf_stats
from utils.rag_store import (
    chroma_available,
    delete_paper,
    embedding_status,
    extract_doi,
    file_digest,
    first_words,
    index_papers,
    search_papers,
    source_label,
    vector_count,
)


APP_NAME = "PaperMind"
MODEL_OPTIONS = ["gemini-2.5-flash", "gemini-2.5-flash-lite"]
STOPWORDS = {
    "the",
    "and",
    "for",
    "with",
    "that",
    "this",
    "from",
    "are",
    "was",
    "were",
    "has",
    "have",
    "into",
    "using",
    "used",
    "based",
    "paper",
    "research",
    "study",
    "results",
    "method",
    "data",
    "model",
    "models",
    "than",
    "their",
    "these",
}


def clean_markdown(text):
    text = html.escape(text)
    text = re.sub(r"\*\*(.*?)\*\*", r"<b>\1</b>", text)
    return text


def create_pdf_report(report_text):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=48,
        leftMargin=48,
        topMargin=46,
        bottomMargin=46,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "PaperMindTitle",
        parent=styles["Title"],
        fontSize=22,
        leading=28,
        spaceAfter=18,
        textColor=colors.HexColor("#1f3a5f"),
    )
    heading_style = ParagraphStyle(
        "PaperMindHeading",
        parent=styles["Heading2"],
        fontSize=14,
        leading=18,
        spaceBefore=14,
        spaceAfter=7,
        textColor=colors.HexColor("#1f3a5f"),
    )
    body_style = ParagraphStyle(
        "PaperMindBody",
        parent=styles["BodyText"],
        fontSize=9.5,
        leading=13,
        spaceAfter=5,
    )
    bullet_style = ParagraphStyle(
        "PaperMindBullet",
        parent=body_style,
        leftIndent=17,
        bulletIndent=7,
    )

    story = [
        Paragraph(APP_NAME, title_style),
        Paragraph("RAG-Powered Research Report", heading_style),
        Paragraph(
            "Generated by an AI research assistant. Review all outputs before academic, clinical, legal, or professional use.",
            body_style,
        ),
        PageBreak(),
    ]

    for line in report_text.splitlines():
        line = line.strip()
        if not line:
            story.append(Spacer(1, 6))
        elif line.startswith("# "):
            story.append(Paragraph(clean_markdown(line[2:]), title_style))
        elif line.startswith("## "):
            story.append(Paragraph(clean_markdown(line[3:]), heading_style))
        elif line.startswith("### "):
            story.append(Paragraph(clean_markdown(line[4:]), heading_style))
        elif line.startswith(("- ", "* ")):
            story.append(Paragraph(clean_markdown(line[2:]), bullet_style, bulletText="•"))
        elif line.startswith("---"):
            story.append(Spacer(1, 10))
        else:
            story.append(Paragraph(clean_markdown(line), body_style))

    doc.build(story)
    buffer.seek(0)
    return buffer


def guess_title(text, fallback="Untitled paper"):
    for line in text.splitlines()[:25]:
        line = re.sub(r"\s+", " ", line).strip()
        if 18 <= len(line) <= 180 and not line.lower().startswith(("abstract", "keywords")):
            return line
    return fallback


def keyword_list(text, limit=12):
    words = re.findall(r"[A-Za-z][A-Za-z\-]{3,}", text.lower())
    counts = Counter(word for word in words if word not in STOPWORDS)
    return counts.most_common(limit)


def basic_citation(paper):
    doi = paper.get("doi")
    suffix = f" https://doi.org/{doi}" if doi else ""
    return f"{paper['title']}. Source file: {paper['file_name']}.{suffix}"


def generate_ai_citation(paper, model_name):
    prompt = f"""
Create a cautious academic citation record from the available PDF metadata and text.

Return:
- Short citation
- APA-style citation if possible
- DOI if present
- Notes about missing metadata

Do not invent authors, venues, years, or page ranges.

Title: {paper['title']}
File name: {paper['file_name']}
Author metadata: {paper['stats'].get('author') or 'Not provided'}
DOI: {paper.get('doi') or 'Not found'}
First 500 words:
{paper['abstract']}
"""
    return run_gemini(prompt, model_name)


def build_paper_profile(paper):
    terms = ", ".join(word for word, _ in keyword_list(paper["text"], 8))
    doi_line = paper.get("doi") or "Not detected"
    return "\n".join(
        [
            f"- Title: {paper['title']}",
            f"- File: {paper['file_name']}",
            f"- Author metadata: {paper['stats'].get('author') or 'Not provided'}",
            f"- Pages with text: {len(paper['pages'])}",
            f"- Words extracted: {paper['word_count']:,}",
            f"- DOI: {doi_line}",
            f"- Top terms: {terms or 'Not enough text extracted'}",
            f"- Working abstract: {paper['abstract'] or 'No readable text extracted.'}",
            "",
            "## Citation",
            paper.get("citation") or basic_citation(paper),
        ]
    )


def build_library_profile(papers):
    if len(papers) == 1:
        return build_paper_profile(papers[0])

    all_terms = Counter()
    for paper in papers:
        all_terms.update(dict(keyword_list(paper["text"], 12)))
    titles = "\n".join(
        f"- Paper {paper['paper_index']}: {paper['title']} ({paper['word_count']:,} words)"
        for paper in papers
    )
    return "\n".join(
        [
            f"- Papers in active context: {len(papers)}",
            f"- Total pages with readable text: {sum(len(paper['pages']) for paper in papers)}",
            f"- Total words extracted: {sum(paper['word_count'] for paper in papers):,}",
            f"- Shared top terms: {', '.join(term for term, _ in all_terms.most_common(12))}",
            "",
            "## Active Papers",
            titles,
        ]
    )


def build_combined_corpus(papers):
    sections = []
    for paper in papers:
        sections.append(
            "\n".join(
                [
                    f"===== PAPER {paper['paper_index']}: {paper['title']} =====",
                    f"File name: {paper['file_name']}",
                    f"DOI: {paper.get('doi') or 'Not detected'}",
                    f"Citation: {paper.get('citation') or basic_citation(paper)}",
                    "",
                    paper["text"],
                ]
            )
        )
    return "\n\n".join(sections)


def prepare_uploaded_papers(uploaded_files, model_name, use_ai_citations):
    papers = []
    errors = []
    next_index = len(st.session_state.get("papers", [])) + 1
    existing_digests = {paper["digest"] for paper in st.session_state.get("papers", [])}

    for uploaded_file in uploaded_files:
        file_bytes = uploaded_file.getvalue()
        digest = file_digest(file_bytes)
        if digest in existing_digests:
            continue

        try:
            stats = get_pdf_stats(uploaded_file)
            pages = extract_pages_from_pdf(uploaded_file)
        except Exception as exc:
            errors.append(f"{uploaded_file.name}: {exc}")
            continue

        text = "\n".join(page["text"] for page in pages)
        if not text.strip():
            errors.append(f"{uploaded_file.name}: no readable text found")
            continue

        paper = {
            "digest": digest,
            "paper_index": next_index,
            "file_name": uploaded_file.name,
            "stats": stats,
            "pages": pages,
            "text": text,
            "title": stats.get("title") or guess_title(text, uploaded_file.name),
            "doi": extract_doi(text),
            "abstract": first_words(text, 500),
            "word_count": len(text.split()),
            "char_count": len(text),
        }
        paper["citation"] = generate_ai_citation(paper, model_name) if use_ai_citations else basic_citation(paper)
        papers.append(paper)
        existing_digests.add(digest)
        next_index += 1

    return papers, errors


def format_inline_markdown(text):
    text = html.escape(text)
    text = re.sub(r"`([^`]+)`", r"<code>\1</code>", text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*([^*]+)\*", r"<em>\1</em>", text)
    return text


def markdown_to_html(text):
    html_parts = []
    in_list = False
    in_code = False
    code_lines = []

    def close_list():
        nonlocal in_list
        if in_list:
            html_parts.append("</ul>")
            in_list = False

    for raw_line in (text or "").splitlines():
        line = raw_line.rstrip()
        if line.strip().startswith("```"):
            if in_code:
                html_parts.append(f"<pre><code>{html.escape(chr(10).join(code_lines))}</code></pre>")
                code_lines = []
                in_code = False
            else:
                close_list()
                in_code = True
            continue
        if in_code:
            code_lines.append(line)
            continue

        stripped = line.strip()
        if not stripped:
            close_list()
            continue
        if stripped.startswith("---"):
            close_list()
            html_parts.append("<hr>")
            continue
        if stripped.startswith("### "):
            close_list()
            html_parts.append(f"<h4>{format_inline_markdown(stripped[4:])}</h4>")
            continue
        if stripped.startswith("## "):
            close_list()
            html_parts.append(f"<h3>{format_inline_markdown(stripped[3:])}</h3>")
            continue
        if stripped.startswith("# "):
            close_list()
            html_parts.append(f"<h2>{format_inline_markdown(stripped[2:])}</h2>")
            continue
        if stripped.startswith(("- ", "* ")):
            if not in_list:
                html_parts.append("<ul>")
                in_list = True
            html_parts.append(f"<li>{format_inline_markdown(stripped[2:])}</li>")
            continue

        close_list()
        html_parts.append(f"<p>{format_inline_markdown(stripped)}</p>")

    close_list()
    if in_code:
        html_parts.append(f"<pre><code>{html.escape(chr(10).join(code_lines))}</code></pre>")
    return "\n".join(html_parts)


def render_response(text):
    st.markdown(f'<div class="pm-response">{markdown_to_html(text)}</div>', unsafe_allow_html=True)


def run_analysis(paper_text, model_name, char_limit):
    steps = [
        ("Summary", lambda: run_summary_agent(paper_text, model_name, char_limit)),
        ("Methodology", lambda: run_methodology_agent(paper_text, model_name, char_limit)),
        ("Evaluation", lambda: run_evaluation_agent(paper_text, model_name, char_limit)),
        ("Claims", lambda: run_claims_agent(paper_text, model_name, char_limit)),
        ("Research Mentor", lambda: run_research_mentor_agent(paper_text, model_name, char_limit)),
    ]

    outputs = {}
    progress = st.progress(0)
    status = st.status("Running multi-agent analysis", expanded=True)
    for index, (name, task) in enumerate(steps, start=1):
        with st.spinner(f"{name} agent is working..."):
            outputs[name] = task()
        progress.progress(int(index / (len(steps) + 1) * 100))
        status.write(f"{name} agent completed")

    with st.spinner("Safety review agent is checking the generated analysis..."):
        outputs["Safety"] = run_safety_agent(
            outputs["Summary"],
            outputs["Methodology"],
            outputs["Evaluation"],
            outputs["Research Mentor"],
            outputs["Claims"],
            model_name,
        )
    progress.progress(100)
    status.update(label="Analysis complete", state="complete", expanded=False)
    return outputs


def answer_with_rag(question, hits, model_name, chat_history):
    context_blocks = []
    for hit in hits:
        metadata = hit["metadata"]
        context_blocks.append(
            f"[{source_label(hit)} | {metadata.get('title')} | DOI: {metadata.get('doi') or 'not detected'}]\n{hit['text']}"
        )
    history = "\n".join(f"{item['role']}: {item['content']}" for item in chat_history[-6:])
    prompt = f"""
You are PaperMind, a critical research assistant.

Answer the user using only the retrieved PDF context where possible.
Use source labels like [Paper 1, p. 4] after claims that come from a source.
If the retrieved context is insufficient, say what is missing.
Be concise, analytical, and avoid overclaiming.

Recent chat:
{history}

Retrieved context:
{chr(10).join(context_blocks)}

Question:
{question}
"""
    return run_gemini(prompt, model_name)


def inject_css():
    st.markdown(
        """
<style>
:root {
    --pm-page: #edf3f8;
    --pm-panel: #ffffff;
    --pm-panel-soft: #f8fafc;
    --pm-text: #102033;
    --pm-muted: #526174;
    --pm-border: #d9e3ef;
    --pm-accent: #2f6fed;
    --pm-accent-2: #0f9f88;
    --pm-warning-bg: #fff8ed;
    --pm-warning-text: #614108;
}
[data-testid="stAppViewContainer"] { background: var(--pm-page); }
[data-testid="stHeader"] { background: rgba(237, 243, 248, 0.9); }
.block-container {
    max-width: 1440px;
    padding-top: 3.2rem;
    padding-bottom: 2.4rem;
    color: var(--pm-text);
}
.block-container p, .block-container li, .block-container label, .block-container span,
.block-container div, .block-container h1, .block-container h2, .block-container h3, .block-container h4 {
    letter-spacing: 0;
}
.block-container .stMarkdown, .block-container .stMarkdown p, .block-container .stMarkdown li,
.block-container .stMarkdown h1, .block-container .stMarkdown h2, .block-container .stMarkdown h3,
.block-container .stMarkdown h4, .block-container .stMarkdown h5, .block-container .stMarkdown h6 {
    color: var(--pm-text);
}
.pm-nav {
    display: flex;
    align-items: center;
    justify-content: space-between;
    gap: 18px;
    padding: 16px 18px;
    border: 1px solid var(--pm-border);
    border-radius: 10px;
    background: var(--pm-panel);
    margin: 6px 0 24px 0;
    min-height: 64px;
    box-shadow: 0 10px 24px rgba(15, 23, 42, 0.05);
}
.pm-brand { font-size: 20px; font-weight: 850; color: var(--pm-text); white-space: nowrap; }
.pm-nav-links { display: flex; gap: 10px; flex-wrap: wrap; justify-content: flex-end; }
.pm-nav-links a {
    color: var(--pm-muted) !important;
    text-decoration: none;
    font-size: 14px;
    font-weight: 700;
    padding: 8px 10px;
    border-radius: 6px;
    line-height: 1.1;
    white-space: nowrap;
}
.pm-nav-links a:hover { background: var(--pm-panel-soft); color: var(--pm-text) !important; }
.pm-hero {
    display: grid;
    grid-template-columns: minmax(0, 1.15fr) minmax(320px, 0.85fr);
    gap: 34px;
    align-items: center;
    color: var(--pm-text);
    padding: 28px 0 24px 0;
    margin-bottom: 18px;
}
.pm-title { font-size: 54px; line-height: 1.05; font-weight: 900; max-width: 760px; }
.pm-subtitle { color: var(--pm-muted); font-size: 17px; line-height: 1.65; max-width: 760px; margin-top: 16px; }
.pm-hero-panel {
    background: linear-gradient(135deg, rgba(47, 111, 237, 0.10), rgba(15, 159, 136, 0.12)), var(--pm-panel);
    border: 1px solid var(--pm-border);
    border-radius: 12px;
    padding: 18px;
    box-shadow: 0 18px 42px rgba(15, 23, 42, 0.10);
}
.pm-mini-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 10px; }
.pm-mini-card {
    background: var(--pm-panel);
    border: 1px solid var(--pm-border);
    border-radius: 8px;
    padding: 14px;
    min-height: 84px;
}
.pm-label {
    color: var(--pm-muted);
    font-size: 12px;
    font-weight: 750;
    text-transform: uppercase;
    letter-spacing: 0;
}
.pm-value { color: var(--pm-text); font-size: 24px; font-weight: 820; margin-top: 2px; }
.pm-section { margin: 28px 0 18px 0; }
.pm-section-title { font-size: 26px; font-weight: 880; color: var(--pm-text); margin-bottom: 8px; }
.pm-section-copy { color: var(--pm-muted); font-size: 15px; line-height: 1.6; max-width: 860px; margin-bottom: 18px; }
.pm-workspace {
    display: grid;
    grid-template-columns: minmax(260px, 0.9fr) minmax(420px, 1.45fr) minmax(280px, 0.95fr);
    gap: 16px;
    align-items: start;
}
.pm-panel {
    background: var(--pm-panel);
    border: 1px solid var(--pm-border);
    border-radius: 10px;
    padding: 16px;
    color: var(--pm-text);
    min-height: 160px;
}
.pm-panel h3 { margin: 0 0 10px 0; color: var(--pm-text); font-size: 18px; }
.pm-card {
    background: var(--pm-panel-soft);
    border: 1px solid var(--pm-border);
    border-radius: 8px;
    padding: 12px;
    margin: 10px 0;
}
.pm-status-ok { color: #0f7b63 !important; font-weight: 800; }
.pm-status-warn { color: #a35d00 !important; font-weight: 800; }
.pm-source {
    background: var(--pm-panel-soft);
    border: 1px solid var(--pm-border);
    border-left: 4px solid var(--pm-accent);
    border-radius: 8px;
    padding: 12px;
    margin: 10px 0;
}
.pm-response {
    background: var(--pm-panel);
    border: 1px solid var(--pm-border);
    border-radius: 8px;
    padding: 16px 18px;
    margin-top: 12px;
    color: var(--pm-text);
    box-shadow: 0 10px 24px rgba(15, 23, 42, 0.06);
}
.pm-response, .pm-response p, .pm-response li, .pm-response div, .pm-response span,
.pm-response strong, .pm-response em, .pm-response td, .pm-response th {
    color: var(--pm-text) !important;
}
.pm-response h1, .pm-response h2, .pm-response h3, .pm-response h4, .pm-response h5, .pm-response h6 {
    color: var(--pm-text) !important;
    margin-top: 0.65rem;
}
.pm-response code {
    color: #0f5132 !important;
    background: #eaf7ef !important;
    border: 1px solid #cdebd8;
    border-radius: 4px;
    padding: 2px 5px;
}
.pm-warning {
    border-left: 4px solid #c78322;
    background: var(--pm-warning-bg);
    color: var(--pm-warning-text);
    padding: 12px 14px;
    border-radius: 8px;
}
.pm-warning, .pm-warning * { color: var(--pm-warning-text) !important; }
.stTextArea textarea, .stTextInput input {
    color: var(--pm-text) !important;
    background: var(--pm-panel) !important;
    border-color: var(--pm-border) !important;
}
button[kind="primary"] { border-radius: 6px; }
.stDownloadButton button {
    background: var(--pm-panel) !important;
    border: 1px solid var(--pm-border) !important;
    border-radius: 7px !important;
    color: var(--pm-text) !important;
}
.stDownloadButton button, .stDownloadButton button *, .stDownloadButton button p,
.stDownloadButton button span, .stDownloadButton button div { color: var(--pm-text) !important; }
.stDownloadButton button:hover {
    border-color: var(--pm-accent) !important;
    background: var(--pm-panel-soft) !important;
    color: var(--pm-text) !important;
}
@media (max-width: 1100px) {
    .pm-hero, .pm-workspace { grid-template-columns: 1fr; }
    .pm-title { font-size: 40px; }
    .pm-nav { align-items: flex-start; flex-direction: column; padding: 14px; }
    .pm-nav-links { justify-content: flex-start; }
}
</style>
""",
        unsafe_allow_html=True,
    )


load_dotenv()
api_key = os.getenv("GEMINI_API_KEY") or os.getenv("GOOGLE_API_KEY")

st.set_page_config(page_title=APP_NAME, page_icon="📚", layout="wide")
inject_css()

if "papers" not in st.session_state:
    st.session_state.papers = []
if "analysis" not in st.session_state:
    st.session_state.analysis = None
if "chat" not in st.session_state:
    st.session_state.chat = []
if "last_hits" not in st.session_state:
    st.session_state.last_hits = []

with st.sidebar:
    st.header("Research Settings")
    default_index = MODEL_OPTIONS.index(DEFAULT_MODEL) if DEFAULT_MODEL in MODEL_OPTIONS else 0
    selected_model = st.selectbox("Gemini model", MODEL_OPTIONS, index=default_index)
    depth = st.radio("Context depth", ["Balanced", "Deep", "Fast"], horizontal=True)
    char_limit = {"Fast": 8000, "Balanced": 16000, "Deep": 26000}[depth]
    top_k = st.slider("RAG sources", 3, 12, 6)
    use_ai_citations = st.toggle("Generate AI citations on upload", value=False)
    show_raw_text = st.toggle("Show extracted text preview", value=False)
    st.divider()
    if "api_key_override" not in st.session_state:
        st.session_state.api_key_override = ""
    api_key_input = st.text_input(
        "Gemini API Key",
        type="password",
        value=st.session_state.api_key_override,
        placeholder="Paste your Gemini API key here (skips .env)",
        help="Optional if set in .env. Overrides .env for this session.",
    )
    if api_key_input != st.session_state.api_key_override:
        if api_key_input:
            os.environ["GEMINI_API_KEY"] = api_key_input
            st.session_state.api_key_override = api_key_input
        else:
            os.environ.pop("GEMINI_API_KEY", None)
            st.session_state.api_key_override = ""
        get_gemini_client.cache_clear()
        st.rerun()
    st.caption("Requires `GEMINI_API_KEY` in `.env` for AI analysis, embeddings, and citations. You can also paste it above.")

st.markdown(
    """
<div class="pm-nav">
    <div class="pm-brand">PaperMind</div>
    <div class="pm-nav-links">
        <a href="#workspace">Workspace</a>
        <a href="#rag-search">RAG Search</a>
        <a href="#report">Report</a>
    </div>
</div>
<section class="pm-hero">
    <div>
        <div class="pm-label">RAG-powered research workspace</div>
        <div class="pm-title">Upload papers, build context, and ask source-grounded questions.</div>
        <div class="pm-subtitle">
            PaperMind now stores uploaded PDFs in a persistent ChromaDB vector index, retrieves the most
            relevant chunks for every question, and keeps paper profiles, citations, DOI metadata, chat,
            search, and report generation in one workflow.
        </div>
    </div>
    <div class="pm-hero-panel">
        <div class="pm-mini-grid">
            <div class="pm-mini-card"><div class="pm-label">Upload</div><div class="pm-value">Multi-PDF</div></div>
            <div class="pm-mini-card"><div class="pm-label">Storage</div><div class="pm-value">ChromaDB</div></div>
            <div class="pm-mini-card"><div class="pm-label">Retrieval</div><div class="pm-value">Semantic</div></div>
            <div class="pm-mini-card"><div class="pm-label">Output</div><div class="pm-value">Cited AI</div></div>
        </div>
    </div>
</section>
<section class="pm-section" id="workspace">
    <div class="pm-section-title">Research Workspace</div>
    <div class="pm-section-copy">
        Use the command bar for uploads, settings, and context health. Then move through the tabs:
        manage the library, search and chat with sources, and generate a final report.
    </div>
</section>
""",
    unsafe_allow_html=True,
)

if not api_key:
    st.error("Gemini API key not found. Add GEMINI_API_KEY to your .env file.")

papers = st.session_state.papers
paper_text = build_combined_corpus(papers) if papers else ""
paper_profile = build_library_profile(papers) if papers else "No papers in active context."
word_count = sum(paper["word_count"] for paper in papers)
readable_pages = sum(len(paper["pages"]) for paper in papers)
char_count = sum(paper["char_count"] for paper in papers)
coverage = (
    min(100, round((min(char_count, char_limit) / max(char_count, 1)) * 100))
    if papers
    else 0
)
active_digests = [paper["digest"] for paper in papers]

metrics = st.container(border=True)
with metrics:
    m1, m2, m3, m4, m5 = st.columns(5)
    m1.metric("Active papers", len(papers))
    m2.metric("Readable pages", readable_pages)
    m3.metric("Extracted words", f"{word_count:,}")
    m4.metric("Vector chunks", vector_count())
    m5.metric("Report coverage", f"{coverage}%")

command_1, command_2, command_3, command_4 = st.columns([1.1, 1, 1, 1])

with command_1:
    with st.popover("Upload PDFs", use_container_width=True):
        uploaded_files = st.file_uploader(
            "Select research PDFs",
            type=["pdf"],
            accept_multiple_files=True,
            help="Upload one or many text-based academic PDFs.",
        )
        if uploaded_files:
            st.caption(f"{len(uploaded_files)} file(s) selected")
        if st.button(
            "Extract and index",
            type="primary",
            use_container_width=True,
            disabled=not api_key or not uploaded_files,
        ):
            try:
                with st.spinner("Extracting text, citations, and vector chunks..."):
                    new_papers, extraction_errors = prepare_uploaded_papers(
                        uploaded_files, selected_model, use_ai_citations
                    )
                    index_result = (
                        index_papers(new_papers)
                        if new_papers
                        else {"indexed": 0, "skipped": 0, "message": "No new papers."}
                    )
                    st.session_state.papers.extend(new_papers)
                    st.session_state.analysis = None
                if extraction_errors:
                    st.warning(
                        "Some files could not be processed:\n\n"
                        + "\n".join(f"- {error}" for error in extraction_errors)
                    )
                st.success(
                    f"{len(new_papers)} paper(s) added. "
                    f"{index_result.get('indexed', 0)} chunks indexed."
                )
            except Exception as exc:
                st.error(
                    "Indexing failed while creating Gemini embeddings. "
                    "The app now auto-detects supported embedding models; if this persists, "
                    "set `GEMINI_EMBEDDING_MODEL=embedding-001` in `.env` and restart."
                )
                st.exception(exc)

with command_2:
    with st.popover("Context Health", use_container_width=True):
        chroma_status = "Ready" if chroma_available() else "Missing dependency"
        embed_status = embedding_status() if api_key else {"selected": "API key missing", "available": []}
        st.write(f"ChromaDB: **{chroma_status}**")
        st.write(f"Embedding model: **{embed_status['selected']}**")
        st.write(f"Active papers: **{len(papers)}**")
        st.write(f"Readable pages: **{readable_pages}**")
        st.write(f"Extracted words: **{word_count:,}**")
        st.write(f"Vector chunks stored: **{vector_count()}**")
        if embed_status.get("available"):
            with st.expander("Available embedding models"):
                st.write(embed_status["available"])
        st.progress(
            coverage / 100 if coverage else 0,
            text=f"Context coverage for report agents: {coverage}%",
        )
        if not chroma_available():
            st.warning("Install `chromadb` from requirements to enable persistent vector search.")

with command_3:
    with st.popover("Workflow Settings", use_container_width=True):
        st.write(f"Model: `{selected_model}`")
        st.write(f"Context depth: `{depth}`")
        st.write(f"RAG sources per query: `{top_k}`")
        st.write(f"AI citations: `{'on' if use_ai_citations else 'off'}`")
        st.caption("Change these values in the sidebar.")

with command_4:
    with st.popover("Session Actions", use_container_width=True):
        if st.button("Clear chat", use_container_width=True):
            st.session_state.chat = []
            st.rerun()
        if st.button("Clear report", use_container_width=True):
            st.session_state.analysis = None
            st.rerun()
        if st.button("Clear active papers", use_container_width=True):
            for paper in st.session_state.papers:
                delete_paper(paper["digest"])
            st.session_state.papers = []
            st.session_state.analysis = None
            st.session_state.last_hits = []
            st.rerun()

library_tab, search_tab, report_tab = st.tabs(["Library", "Search & Chat", "Report Studio"])

with library_tab:
    st.subheader("Active Library")
    if not papers:
        st.info("Upload and index PDFs from the command bar to begin.")
    else:
        left_col, right_col = st.columns([1.2, 0.8], gap="large")
        with left_col:
            st.container(border=True).markdown("#### Library Profile")
            render_response(paper_profile)
        with right_col:
            st.container(border=True).markdown("#### Top Terms")
            term_grid = st.columns(2)
            for index, (term, count) in enumerate(keyword_list(paper_text, 12)):
                term_grid[index % 2].metric(term, count)

        st.divider()
        st.markdown("#### Papers")
        for paper in papers:
            paper_box = st.container(border=True)
            with paper_box:
                title_col, meta_col, action_col = st.columns([1.8, 1, 0.8])
                title_col.markdown(f"**Paper {paper['paper_index']}: {paper['title']}**")
                meta_col.caption(f"{paper['word_count']:,} words · {len(paper['pages'])} pages")
                with action_col:
                    with st.popover("Details", use_container_width=True):
                        render_response(build_paper_profile(paper))
                        if st.button("Remove from context", key=f"remove-{paper['digest']}"):
                            delete_paper(paper["digest"])
                            st.session_state.papers = [
                                item for item in st.session_state.papers if item["digest"] != paper["digest"]
                            ]
                            st.session_state.analysis = None
                            st.rerun()

        if show_raw_text:
            st.divider()
            selected_preview = st.selectbox(
                "Preview extracted text",
                ["Combined corpus"]
                + [f"Paper {paper['paper_index']}: {paper['title']}" for paper in papers],
            )
            if selected_preview == "Combined corpus":
                preview_text = paper_text
            else:
                selected_index = int(selected_preview.split(":", 1)[0].replace("Paper ", "")) - 1
                preview_text = papers[selected_index]["text"]
            st.text_area("Extracted text", preview_text[:12000], height=280)

with search_tab:
    st.subheader("Semantic Search")
    search_box = st.container(border=True)
    with search_box:
        search_query = st.text_input(
            "Search active context",
            placeholder="Example: What datasets and evaluation metrics are used?",
        )
        if st.button(
            "Search context",
            type="primary",
            use_container_width=True,
            disabled=not api_key or not chroma_available() or not search_query.strip(),
        ):
            st.session_state.last_hits = search_papers(
                search_query, top_k=top_k, digests=active_digests or None
            )

    if st.session_state.last_hits:
        st.markdown("#### Retrieved Sources")
        for index, hit in enumerate(st.session_state.last_hits, start=1):
            metadata = hit["metadata"]
            source_box = st.container(border=True)
            with source_box:
                st.markdown(
                    f"**{index}. {source_label(hit)}** · {metadata.get('title', 'Untitled')} · score `{hit['score']:.2f}`"
                )
                st.caption((hit["text"][:520] + "...") if len(hit["text"]) > 520 else hit["text"])
                with st.popover("Full source"):
                    st.write(hit["text"])
                    st.write(f"DOI: `{metadata.get('doi') or 'Not detected'}`")
                    st.write(f"File: `{metadata.get('file_name', 'Unknown')}`")

    st.divider()
    st.subheader("Ask PaperMind")
    chat_area = st.container(border=True)
    with chat_area:
        if not st.session_state.chat:
            st.caption("Ask a question after indexing PDFs. Answers will use retrieved paper chunks.")
        for message in st.session_state.chat:
            with st.chat_message(message["role"]):
                st.markdown(message["content"])

    question = st.chat_input("Ask a source-grounded question")
    if question:
        st.session_state.chat.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)
        with st.chat_message("assistant"):
            if not api_key:
                answer = "Add `GEMINI_API_KEY` to `.env` before using chat."
            elif not chroma_available():
                answer = "ChromaDB is not installed. Install requirements and restart the app to enable RAG chat."
            elif not papers:
                answer = "Upload and index PDFs before asking research questions."
            else:
                hits = search_papers(question, top_k=top_k, digests=active_digests or None)
                st.session_state.last_hits = hits
                answer = answer_with_rag(question, hits, selected_model, st.session_state.chat)
            st.markdown(answer)
        st.session_state.chat.append({"role": "assistant", "content": answer})

with report_tab:
    st.subheader("Report Studio")
    if not papers:
        st.info("Upload and index PDFs before generating a report.")
    else:
        report_controls = st.container(border=True)
        with report_controls:
            st.write("Generate the multi-agent report from the active paper context.")
            if st.button(
                "Run Multi-Agent Report",
                type="primary",
                use_container_width=True,
                disabled=not api_key,
            ):
                try:
                    st.session_state.analysis = run_analysis(paper_text, selected_model, char_limit)
                except Exception as exc:
                    st.error(
                        "The analysis could not be completed. Check API quota, model access, and network availability."
                    )
                    st.exception(exc)

        if st.session_state.analysis:
            analysis = st.session_state.analysis
            final_report = generate_final_report(
                paper_profile,
                analysis["Summary"],
                analysis["Methodology"],
                analysis["Evaluation"],
                analysis["Claims"],
                analysis["Research Mentor"],
                analysis["Safety"],
            )
            pdf_report = create_pdf_report(final_report)
            report_tabs = st.tabs(["Summary", "Method", "Evaluation", "Claims", "Mentor", "Safety", "Final"])
            with report_tabs[0]:
                render_response(analysis["Summary"])
            with report_tabs[1]:
                render_response(analysis["Methodology"])
            with report_tabs[2]:
                render_response(analysis["Evaluation"])
            with report_tabs[3]:
                render_response(analysis["Claims"])
            with report_tabs[4]:
                render_response(analysis["Research Mentor"])
            with report_tabs[5]:
                render_response(analysis["Safety"])
                st.markdown(
                    '<div class="pm-warning">Human review is required before using this analysis for academic, clinical, legal, or professional decisions.</div>',
                    unsafe_allow_html=True,
                )
            with report_tabs[6]:
                render_response(final_report)
                download_col_1, download_col_2 = st.columns(2)
                with download_col_1:
                    st.download_button(
                        "Download Markdown",
                        final_report,
                        "papermind_research_report.md",
                        "text/markdown",
                        use_container_width=True,
                    )
                with download_col_2:
                    st.download_button(
                        "Download PDF",
                        pdf_report,
                        "papermind_research_report.pdf",
                        "application/pdf",
                        use_container_width=True,
                    )
        else:
            st.caption("No report generated yet.")
