def generate_final_report(paper_profile, summary, methodology, evaluation, claims, future_work, safety_review):
    return f"""
# PaperMind Research Report

## Paper Profile
{paper_profile}

---

## 1. Summary
{summary}

---

## 2. Methodology
{methodology}

---

## 3. Evaluation
{evaluation}

---

## 4. Claims and Evidence
{claims}

---

## 5. Research Mentor Notes
{future_work}

---

## 6. Safety Review
{safety_review}

---

## Human Review Notice

This report was generated by an AI-powered multi-agent system. It should be reviewed by a human researcher before academic, clinical, legal, or professional use.

Generated by PaperMind.
"""
